### ISSUE TITLE
uncatchable java.lang.IllegalArgumentException upon configuration change

### ISSUE THREAD

**Issue by gentledepp** [Redth/AndHUD#11]
Hi!
Me again. 
I am using a background process (Task) to load some viewmodels (using MvvmCross) and I just want to display the progress of this action using AndHUD.Shared.Show("loading", <someNumber>)
That works fine now as long as I do not change the orientation of my device. As soon as I do that, I get a java.lang.IllegarArgumentException. Unfortumately I cannot catch that with Xamarin. 

To be more precise: I call "Show('loading', <someNumber) several times in my background thread. As soon as the configuration change takes place, the very next call to that method results in the "illegalArgumentException"

Might be related to the following Stackoverflow post: http://stackoverflow.com/questions/2745061/java-lang-illegalargumentexception-view-not-attached-to-window-manager

**Comment by jessejiang0214** [comment]
Hi 
I meet a similar problem on Xamarin Forms background process. When I first call UserDialogs.Instance.Loading("Loading"), I got error with 
View=com.android.internal.policy.impl.PhoneWindow$DecorView{16c9ef87 G.E..... R.....I. 0,0-0,0} not attached to window manager

But I call it in second time, everything is OK.

AcrUserDialogs versin is 4.1.4

Thanks
Call stack is here 
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.IllegalArgumentException: Exception of type 'Java.Lang.IllegalArgumentException' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
[MonoDroid] at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr) [0x00062] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:554
[MonoDroid] at Android.App.Dialog.Dismiss () [0x00043] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.App.Dialog.cs:558
[MonoDroid] at AndroidHUD.AndHUD/<DismissCurrent>c__AnonStorey4.<>m__0 () <IL 0x0001c, 0x00075>
[MonoDroid] at AndroidHUD.AndHUD/<DismissCurrent>c__AnonStorey4.<>m__1 (object) <IL 0x00006, 0x00028>
[MonoDroid] at Android.App.SyncContext.Send (System.Threading.SendOrPostCallback,object) [0x00025] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:26
[MonoDroid] at AndroidHUD.AndHUD.DismissCurrent (Android.Content.Context) <IL 0x00067, 0x00294>
[MonoDroid] at AndroidHUD.AndHUD.showStatus (Android.Content.Context,bool,string,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,bool,System.Action) <IL 0x0006d, 0x0025f>
[MonoDroid] at AndroidHUD.AndHUD.Show (Android.Content.Context,string,int,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,bool,System.Action) <IL 0x0002c, 0x0015b>
[MonoDroid] at Acr.UserDialogs.ProgressDialog/<>c__DisplayClass28_0.<Refresh>b__0 () [0x00000] in C:\dev\plugins\userdialogs\src\Acr.UserDialogs.Android\ProgressDialog.cs:110
[MonoDroid] at Acr.Support.Android.Extensions.RequestMainThread (System.Action) <IL 0x0001f, 0x000b8>
[MonoDroid] at Acr.UserDialogs.ProgressDialog.Refresh () [0x000a5] in C:\dev\plugins\userdialogs\src\Acr.UserDialogs.Android\ProgressDialog.cs:110
[MonoDroid] at Acr.UserDialogs.ProgressDialog.Show () [0x00010] in C:\dev\plugins\userdialogs\src\Acr.UserDialogs.Android\ProgressDialog.cs:72
[MonoDroid] at Acr.UserDialogs.AbstractUserDialogs.Progress (Acr.UserDialogs.ProgressDialogConfig) [0x0004d] in C:\dev\plugins\userdialogs\src\Acr.UserDialogs.Interface\AbstractUserDialogs.cs:98
[MonoDroid] at Acr.UserDialogs.AbstractUserDialogs.Loading (string,System.Action,string,bool,System.Nullable`1<Acr.UserDialogs.MaskType>) [0x00000] in C:\dev\plugins\userdialogs\src\Acr.UserDialogs.Interface\AbstractUserDialogs.cs:65
[MonoDroid] at HappiestHour.ViewModels.LoginViewModel/<TrySocialLogin>c__async0.<>m__0 () [0x00017] in /Users/jesse/Documents/Project/happiesthour-app/HappiestHour/ViewModels/LoginViewModel.cs:61
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.240a1603-7356-426e-ae9e-1fe8092c6c22 (intptr,intptr) <IL 0x00011, 0x0001f>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{16c9ef87 G.E..... R.....I. 0,0-0,0} not attached to window manager
[MonoDroid] 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
[MonoDroid] 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
[MonoDroid] 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
[MonoDroid] 	at android.app.Dialog.dismissDialog(Dialog.java:341)
[MonoDroid] 	at android.app.Dialog.dismiss(Dialog.java:324)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[MonoDroid] 	at android.app.Activity.runOnUiThread(Activity.java:5293)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:739)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:135)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:372)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by petersondrew** [comment]
I've submitted #23 to fix this as I ran into it as well.
