### ISSUE TITLE
AndHUD.Shared.Dismiss on a view that had been closed causes exception - how to handle this?

### ISSUE THREAD

**Issue by tweek82** [Redth/AndHUD#18]
Hi all, hi @Redth,

First of all, thank you for another great component (like PushSharp) and this AndHud.

I've got a WebView. On the webview I've added two eventHandlers for OnPageStarted and OnPageFinished. Both call AndHUD.Shared.Show and AndHUD.Shared.Dismiss and this works perfectly. 

Then the following situation. I execute the this Javascript inside the WebView:

    <div style="display: none">
    <a href="https://myhost.com/default.aspx#appclosecommand" id="CloseThisView" class="btn btn-success">Continue</a>
    </div>
    <script type="text/javascript">
    var link = document.getElementById('CloseThisView'),
    event = document.createEvent('HTMLEvents');
    
    event.initEvent('click', true, true);
    link.dispatchEvent(event);
    </script>

I catch this event using:

    public override bool ShouldOverrideUrlLoading(WebView view, string url)

Then I use the Close command from MvvmCross inside the ViewModel:

    private void GoToDashboardCommandExecute()
    {
     Close(this);
    }

This causes the view to close. This works nice. But, after this, the 'OnPageFinished' is called. And by that, the AndHUD.Shared.Dismiss is called. On a view that doesn't exist anymore. Causing an illigalargument-exception.

How can I handle this nicely? Perhaps I can do a check before calling Dismiss. For now I've got try-catch around the Dismiss method, but that ain't the nicest solution I think.

Any help/tips would be appriciated.

Many thanks in advance,
Eric

11-12 09:25:30.599 E/WindowManager( 3020): Activity md5ac38a9d6af40b058a648f5e3b4a2d104.OnlineView has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@428f3f30 that was originally added here
11-12 09:25:30.599 E/WindowManager( 3020): android.view.WindowLeaked: Activity md5ac38a9d6af40b058a648f5e3b4a2d104.OnlineView has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@428f3f30 that was originally added here
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:380)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:292)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:224)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:149)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.view.Window$LocalWindowManager.addView(Window.java:547)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.app.Dialog.show(Dialog.java:277)
11-12 09:25:30.599 E/WindowManager( 3020): 	at md5bcb6a4543e7a4af455649c39f2e90558.MyWebViewClient.n_onPageStarted(Native Method)
11-12 09:25:30.599 E/WindowManager( 3020): 	at md5bcb6a4543e7a4af455649c39f2e90558.MyWebViewClient.onPageStarted(MyWebViewClient.java:39)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:325)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.os.Looper.loop(Looper.java:137)
11-12 09:25:30.599 E/WindowManager( 3020): 	at android.app.ActivityThread.main(ActivityThread.java:4838)
11-12 09:25:30.599 E/WindowManager( 3020): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-12 09:25:30.599 E/WindowManager( 3020): 	at java.lang.reflect.Method.invoke(Method.java:511)
11-12 09:25:30.599 E/WindowManager( 3020): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
11-12 09:25:30.599 E/WindowManager( 3020): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
11-12 09:25:30.599 E/WindowManager( 3020): 	at dalvik.system.NativeStart.main(Native Method)
11-12 09:25:36.179 I/MonoDroid( 3020): UNHANDLED EXCEPTION:
11-12 09:25:36.289 I/MonoDroid( 3020): Java.Lang.IllegalArgumentException: Exception of type 'Java.Lang.IllegalArgumentException' was thrown.
11-12 09:25:36.289 I/MonoDroid( 3020): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2185/53fce373/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
11-12 09:25:36.289 I/MonoDroid( 3020): at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr) [0x00062] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:554
11-12 09:25:36.289 I/MonoDroid( 3020): at Android.App.Dialog.Dismiss () [0x00043] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Dialog.cs:558
11-12 09:25:36.289 I/MonoDroid( 3020): at AndroidHUD.AndHUD/<DismissCurrent>c__AnonStorey4.<>m__0 () <IL 0x0001c, 0x000d3>
11-12 09:25:36.289 I/MonoDroid( 3020): at AndroidHUD.AndHUD/<DismissCurrent>c__AnonStorey4.<>m__1 (object) <IL 0x00006, 0x00057>
11-12 09:25:36.289 I/MonoDroid( 3020): at Android.App.SyncContext.Send (System.Threading.SendOrPostCallback,object) [0x00025] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:26
11-12 09:25:36.289 I/MonoDroid( 3020): at AndroidHUD.AndHUD.DismissCurrent (Android.Content.Context) <IL 0x00067, 0x003ef>
11-12 09:25:36.289 I/MonoDroid( 3020): at AndroidHUD.AndHUD.Dismiss (Android.Content.Context) <IL 0x00003, 0x0005b>

**Comment by tweek82** [comment]
Oke. I might be a little to early with posting this issue/question. I've solved this a bit more nicely. Instead of try-catch, I've just added:

        private void GoToDashboardCommandExecute()
        {
            base.IsViewClosed = true;
            Close(this);
        }

Before calling the Dismiss method, I check the IsViewClosed property. Works very nice for now.

**Comment by Redth** [comment]
:) Glad to hear it! :+1:
