### ISSUE TITLE
Internal showStatus call Dismissing Previous Dialog no matter what. 

### ISSUE THREAD

**Issue by Jtdawgzone** [Redth/AndHUD#19]
Ln 95 of AndHUD.cs: DismissCurrent (context);
seems to be the problem.

There are already checks to dismiss the current dialog if necessary or to just update the text, and this line doesn't exist in showImage or showProgress. 

Easy to see if you set the MaskType to black and try re-calling Show with no progress given.

**Comment by Jtdawgzone** [comment]
Created a pull request with this fix.

**Comment by Cheesebaron** [comment]
Fixed https://github.com/Redth/AndHUD/commit/ac8aaa97a2166b9da586e8019faddcb72ffeaf51#diff-05d5dd85272d7cedb2e59ca16d832f52
