### ISSUE TITLE
Change message without dismissing and showing dialog

### ISSUE THREAD

**Issue by ehmason** [Redth/AndHUD#29]
I have an issue/feature I am trying to get working.  I am able to use the project just fine.  However, when using the Show function I am having to show without a progress which should take me into the showStatus function.  Let's say my application is processing 20 different messages.  for each one that is shown it appears that the dialog is dismissing and then showing again for each message.  I would rather just change the message and keep the same dialog open.  So, I began looking for a solution to this.  When looking at the showStatus function within AndHud is it not a bug that the function is going to call DismissCurrent (context); without any criteria?  This is the 3rd statement in the function.  The 4th and 5th actually has criteria before the DismissCurrent is called.  Looking at the else of the "if (CurrentDialog == null)" seems like it would do what I want it to but I believe because of the dismiss that is happening it will never keep the same dialog open and just change the text. Is this correct?

**Comment by ehmason** [comment]
I think my assumption was correct.  When using the progress parameter which goes through the showProgress function the dialog is not dismissed first and instead just changes the text of the dialog.

**Comment by Cheesebaron** [comment]
Re-open if this is still an issue.
