### ISSUE TITLE
In Android 7.0 not showing the process

### ISSUE THREAD

**Issue by Jeevamca** [Redth/AndHUD#30]
Hi We have an issue on Android 7.0, 

We used the below statement to display the process percentage in Android. 
Its works well till Android 6.0.1 

AndHUD.Shared.Show(Forms.Context, "Loading... " + percentage + "%", percentage, MaskType.Clear);

In Andorid 7.0 
It's shows always Loading...0% . Could you please help me on this.

**Comment by Cheesebaron** [comment]
Re-open if it is still an issue.
