### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by MichaelRumpler** [Redth/AndHUD#33]
Xamarin announced that they will discontinue the component store in favor of NuGet. But the AndHUD version in the component store is 1.3.1 and on NuGet 1.2.0.

Please update the NuGet package.

**Comment by rspl-nilesh** [comment]
@MichaelRumpler  Does the 1.3.1 has the fix that "jz5 branch" has ? because I see master branch is behind this branch

**Comment by Cheesebaron** [comment]
Working on it, will release a new package soon.

**Comment by Cheesebaron** [comment]
It is up. Please report any bugs and issues you encounter 👍
