### ISSUE TITLE
And HUD Show spinner like disabled state when something happening on mainthread

### ISSUE THREAD

**Issue by iamvignesh** [Redth/AndHUD#34]
<img width="199" alt="screen shot 2018-01-19 at 2 48 40 pm" src="https://user-images.githubusercontent.com/7777632/35143539-e3c3b24c-fd27-11e7-9e4a-600b96804b96.png">

My app is a BIM app and I am using loading indicator frequently while user is working on 3d model, 
The loading indicator sometimes appears like disabled(like in attached image) when we render 3d model in the background,
But we are able to convince our UAT team that this is obvious bug since both (loading indicator and 3d rendereing) are happening on main thread

But our real problem is that. AndHUD changed permanently (like in attached image) in other parts of the app as well, even though  that actions are background actions.

we even tried to create new AndHUD for all loading instead of using AndHUD.Shared but still no use.

**Comment by Cheesebaron** [comment]
If you are blocking the main thread, then the spinner won't run. Such is life.
