### ISSUE TITLE
Method not found when called via UserDialogs

### ISSUE THREAD

**Issue by steverichey** [Redth/AndHUD#41]
When calling `UserDialogs.Instance.Progress(new ProgressDialogConfig { Title = "title" });` when using Acr.UserDialogs 7.0.1 and AndHUD 1.4.1, I get the following exception:

```
System.MissingMethodException has been thrown
Method not found: void AndroidHUD.AndHUD.Show(Android.Content.Context,string,int,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,bool,System.Action)
  at Acr.UserDialogs.Extensions+<>c__DisplayClass2_0.<SafeRunOnUi>b__0 () [0x00000] in <73df0cb700aa467eaaf0c6c42f01763a>:0 
```

This works when using AndHUD 1.2.0, which makes it seem like a breaking change or bug was introduced in 1.4.1. There is a related issue in UserDialogs [here](https://github.com/aritchie/userdialogs/issues/582).

**Comment by Cheesebaron** [comment]
Hey @steverichey, I think this should be solved by having @aritchie build against the new version of AndHUD. Method signatures didn't change in AndHUD, so the reason is probably because it is built with a much newer version of the Xamarin.Android SDK.

**Comment by Cheesebaron** [comment]
I've opened a PR on the UserDialogs repo: https://github.com/aritchie/userdialogs/pull/585

**Comment by Cheesebaron** [comment]
I believe this is fixed now @steverichey
