### ISSUE TITLE
java error code 2

### ISSUE THREAD

**Issue by matt2003** [Redth/AndHUD#42]
Hi,
I cannot get andhud to compile in with either the nuget or the project from github.
I am using android.support v28, tried 1.41 and 1.2. Clean build remove bin and obj etc.
And help would be appreciated.

I also set to multidex enabled through project options, tried the proguard / enable disable. 

Thanks,
Matt
Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error MSB6006: "java" exited with code 2.

**Comment by Cheesebaron** [comment]
Can you please provide more information or a small repro sample where I can see this issue?

The full error message with stack would help

**Comment by matt2003** [comment]
I get the the error on compilation so no stack trace here is the output with multidex on
UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:548)
    	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
    	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
    	at com.android.dx.command.dexer.Main.main(Main.java:247)
    	at com.android.dx.command.Main.main(Main.java:94)

**Comment by matt2003** [comment]
I had also updated proguard from the site and its supporting files

**Comment by matt2003** [comment]
I found a workaround here 
https://github.com/xamarin/xamarin-android/issues/2919
As the nice gentleman mentions in the other post adding this to the projectgroup in the csproj file works. Apparently this is the equivalent setting that could be passed to gradle had we been doing it the native way.
<DxExtraArguments>--dex --no-strict --force-jumbo</DxExtraArguments>
<AndroidMultiDexClassListExtraArgs>--disable-annotation-resolution-workaround</AndroidMultiDexClassListExtraArgs>

**Comment by Cheesebaron** [comment]
@matt2003 thanks for the clarification!
