### ISSUE TITLE
loading.axml missing content

### ISSUE THREAD

**Issue by PhilJenson** [Redth/AndHUD#49]
Within our app when we call Show(this, "Please wait") from the MainActivity, the background goes dark but the Progress wheel and text is not seen. This used to work okay and works correctly in a demo app trying reproduce it, so the issue clearly lies with our xamarin forms project.

We have included the AndHUD project within our code to find the cause, and it appears that the content of Resource.Layout.loading is empty when running the code. It contains no ProgressBar and no TextView, even though they are present at design time. For example, view.FindViewById<TextView>(Resource.Id.textViewStatus) within showStatus returns null.

After many days investigating we cannot find out why the content should be missing. Does anybody have any idea?

**Comment by Cheesebaron** [comment]
Do you have a layout in your own project named loading?

**Comment by PhilJenson** [comment]
That was something I had not considered. 

I have now change loading.xaml to loading2.xaml (within the AndHUD project) and modified the AndHUD.Show routine to use this instead. I get the same results, so I do not think, should I have a view with the same name,  this is the cause.

**Comment by Cheesebaron** [comment]
When you are testing is it release mode or debug mode? I am not able to reproduce your issue in any of my projects.

**Comment by PhilJenson** [comment]
Primarily we have tested under debug mode, but I have just re-tested release mode and it is the same. 

I too cannot reproduce this out side of the main project so I have to conclude it is unique to our project. I am reaching out as I have run out of ideas so your previous suggestion was most welcome.

**Comment by Cheesebaron** [comment]
Well the only thing that would have any impact would be if you have any of the following layout names in your own Android project:

```
- Resources
    - layout
        - loading.axml
        - loadingimage.axml
        - loadingprogress.axml
```

That would override the ones AndHUD provides.

**Comment by PhilJenson** [comment]
There is a Resources/layout folder in our project but it does not include any of these file names. In addition the names within the AndHUD project have been changed to myloading2.axml, myloadingimage2.axml & myloadingprogress2.axml and it still behaves the same.

**Comment by Cheesebaron** [comment]
Sorry, don't know what is going on. Without being able to reproduce it I can't fix it.

**Comment by PhilJenson** [comment]
I have copied all the files from the AndHUD project to our top level Android project and this all works. Whilst I would have preferred a solution which would allows us to use the nuget package this is acceptable.

I will close this issue as the cause is totally down to our project not AndHUD.

@Cheesebaron Thanks for your help
